__all__ = (
    'IP_TYPE_IP_V4', 'IP_TYPE_IP_V6', 'NAME_SERVER_CONFIGURATION_SECURE_CONNECTION_SUPPORT_LEVEL_MAYBE',
    'NAME_SERVER_CONFIGURATION_SECURE_CONNECTION_SUPPORT_LEVEL_NO',
    'NAME_SERVER_CONFIGURATION_SECURE_CONNECTION_SUPPORT_LEVEL_YES', 'QUERY_TRANSPORT_TYPE_AUTO',
    'QUERY_TRANSPORT_TYPE_TCP', 'QUERY_TRANSPORT_TYPE_TLS', 'QUERY_TRANSPORT_TYPE_UDP',
    'RESPONSE_PARSING_ERROR_CODE_HEADER_OUT_OF_BOUND', 'RESPONSE_PARSING_ERROR_CODE_LABEL_JUMP_FORWARD',
    'RESPONSE_PARSING_ERROR_CODE_LABEL_JUMP_READ_OUT_OF_BOUND',
    'RESPONSE_PARSING_ERROR_CODE_LABEL_LENGTH_INVALID_RANGE',
    'RESPONSE_PARSING_ERROR_CODE_LABEL_LENGTH_READ_OUT_OF_BOUND',
    'RESPONSE_PARSING_ERROR_CODE_LABEL_READ_END_OUT_OF_BOUND',
    'RESPONSE_PARSING_ERROR_CODE_QUESTION_HEADER_OUT_OF_BOUND',
    'RESPONSE_PARSING_ERROR_CODE_RESOURCE_RECORD_DATA_OUT_OF_BOUND',
    'RESPONSE_PARSING_ERROR_CODE_RESOURCE_RECORD_HEADER_OUT_OF_BOUND',
)

from re import compile as re_compile

# Ip related constants

IP_TYPE_NONE = 0
IP_TYPE_IP_V4 = 1
IP_TYPE_IP_V6 = 2


IP_V4_RP = re_compile(
    '([0-9]|[1-9][0-9]|1[0-9][0-9]|2(?:[0-4][0-9]|5[0-5]))\\.'
    '([0-9]|[1-9][0-9]|1[0-9][0-9]|2(?:[0-4][0-9]|5[0-5]))\\.'
    '([0-9]|[1-9][0-9]|1[0-9][0-9]|2(?:[0-4][0-9]|5[0-5]))\\.'
    '([0-9]|[1-9][0-9]|1[0-9][0-9]|2(?:[0-4][0-9]|5[0-5]))'
)
IP_V6_RP = re_compile(
    '([0-9a-f]{1,4})\\:([0-9a-f]{1,4})\\:([0-9a-f]{1,4})\\:([0-9a-f]{1,4})\\:'
    '([0-9a-f]{1,4})\\:([0-9a-f]{1,4})\\:([0-9a-f]{1,4})\\:([0-9a-f]{1,4})'
)

IP_V6_RP_WITH_COLON_AT_START = re_compile(
    '\\:\\:(?:(?:(?:(?:(?:(?:([0-9a-f]{1,4})\\:)?([0-9a-f]{1,4})\\:)?([0-9a-f]{1,4})\\:)?'
    '([0-9a-f]{1,4})\\:)?([0-9a-f]{1,4})\\:)?([0-9a-f]{1,4})\\:)?([0-9a-f]{1,4})'
)
IP_V6_WITH_COLON_AT_END = re_compile(
    '([0-9a-f]{1,4})(?:\\:([0-9a-f]{1,4})(?:\\:([0-9a-f]{1,4})(?:\\:([0-9a-f]{1,4})(?:\\:'
    '([0-9a-f]{1,4})(?:\\:([0-9a-f]{1,4})(?:\\:([0-9a-f]{1,4}))?)?)?)?)?)?\\:\\:'
)
IP_V6_WITH_COLON_IN_MIDDLE = re_compile(
    '([0-9a-f]{1,4})(?:\\:([0-9a-f]{1,4})(?:\\:([0-9a-f]{1,4})(?:\\:([0-9a-f]{1,4})(?:\\:'
    '([0-9a-f]{1,4})(?:\\:([0-9a-f]{1,4}))?)?)?)?)?'
    '\\:\\:'
    '(?:(?:(?:(?:(?:([0-9a-f]{1,4})\\:)?([0-9a-f]{1,4})\\:)?([0-9a-f]{1,4})\\:)?'
    '([0-9a-f]{1,4})\\:)?([0-9a-f]{1,4})\\:)?([0-9a-f]{1,4})'
)
IP_V6_COLON_ONLY = '::'

SPLIT_IP_V6_AND_SCOPE_RP = re_compile(
    '([0-9a-f]{1,4}\\:[0-9a-f]{1,4}\\:[0-9a-f]{1,4}\\:[0-9a-f]{1,4})\\:'
    '([0-9a-f]{1,4}\\:[0-9a-f]{1,4}\\:[0-9a-f]{1,4}\\:[0-9a-f]{1,4})'
    '(?:%(.+)?)?'
)

# Parsing constants

RESPONSE_PARSING_ERROR_CODE_NONE = 0
RESPONSE_PARSING_ERROR_CODE_LABEL_LENGTH_INVALID_RANGE = 1
RESPONSE_PARSING_ERROR_CODE_LABEL_JUMP_FORWARD = 2
RESPONSE_PARSING_ERROR_CODE_LABEL_LENGTH_READ_OUT_OF_BOUND = 3
RESPONSE_PARSING_ERROR_CODE_LABEL_READ_END_OUT_OF_BOUND = 4
RESPONSE_PARSING_ERROR_CODE_LABEL_JUMP_READ_OUT_OF_BOUND = 5
RESPONSE_PARSING_ERROR_CODE_HEADER_OUT_OF_BOUND = 6
RESPONSE_PARSING_ERROR_CODE_QUESTION_HEADER_OUT_OF_BOUND = 7
RESPONSE_PARSING_ERROR_CODE_RESOURCE_RECORD_HEADER_OUT_OF_BOUND = 8
RESPONSE_PARSING_ERROR_CODE_RESOURCE_RECORD_DATA_OUT_OF_BOUND = 9

# Query protocol related contents

QUERY_TRANSPORT_TYPE_AUTO = 0
QUERY_TRANSPORT_TYPE_UDP = 1
QUERY_TRANSPORT_TYPE_TCP = 2
QUERY_TRANSPORT_TYPE_TLS = 3

# Configuration constants

RESOLVE_CONFIGURATION_PATH = '/etc/resolv.conf'

OPTION_REQUIRED_DOT_COUNT_THRESHOLD_LOWER = 1
OPTION_REQUIRED_DOT_COUNT_THRESHOLD_UPPER = 30
OPTION_REQUIRED_DOT_COUNT_DEFAULT = 1

OPTION_TIMEOUT_THRESHOLD_LOWER = 1.0
OPTION_TIMEOUT_THRESHOLD_UPPER = 30.0
OPTION_TIMEOUT_DEFAULT = 5.0

OPTION_ATTEMPTS_THRESHOLD_LOWER = 1
OPTION_ATTEMPTS_THRESHOLD_UPPER = 5
OPTION_ATTEMPTS_DEFAULT = 2


NAME_SERVER_CONFIGURATION_SECURE_CONNECTION_SUPPORT_LEVEL_NO = 0
NAME_SERVER_CONFIGURATION_SECURE_CONNECTION_SUPPORT_LEVEL_YES = 1
NAME_SERVER_CONFIGURATION_SECURE_CONNECTION_SUPPORT_LEVEL_MAYBE = 2


# On a previous test scenario it supported multiple queries at once
NAME_SERVERS_FALLBACK_DEFAULT = (
    (
        IP_TYPE_IP_V4,
        (8 << 24) | (8 << 16) | (8 << 8) | (8 << 0),
        False,
        NAME_SERVER_CONFIGURATION_SECURE_CONNECTION_SUPPORT_LEVEL_YES,
    ),
    (
        IP_TYPE_IP_V4,
        (8 << 24) | (8 << 16) | (4 << 8) | (4 << 0),
        False,
        NAME_SERVER_CONFIGURATION_SECURE_CONNECTION_SUPPORT_LEVEL_YES,
    ),
)

SEARCHES_FALLBACK_DEFAULT = (
    (b'localhost', ),
)

RESOLVE_MD_IP_TYPE = IP_TYPE_IP_V4
RESOLVE_MD_IP_VALUE = (127 << 24) | (0 << 16) | (0 << 8) | (53 << 0)
RESOLVE_MD_CONFIGURATION_PATHS = (
    ('/etc/systemd', False, 'resolved.conf'),
    ('/run/systemd', False, 'resolved.conf'),
    ('/usr/local/lib/systemd', False, 'resolved.conf'),
    ('/usr/lib/systemd/', False, 'resolved.conf'),
    ('/etc/systemd/resolved.conf.d', True, '.conf'),
    ('/run/systemd/resolved.conf.d', True, '.conf'),
    ('/usr/local/lib/systemd/resolved.conf.d', True, '.conf'),
    ('/usr/lib/systemd/resolved.conf.d', True, '.conf'),
)


# Serialisation limits

LABEL_LENGTH_THRESHOLD_UPPER = 63


# Query & response values

MESSAGE_TYPE_SHIFT = 15
OPERATION_CODE_SHIFT = 11
AUTHORITATIVE_ANSWER = 10
TRUNCATED_SHIFT = 9
RECURSION_DESIRED_SHIFT = 8
RECURSION_AVAILABLE_SHIFT = 7
DATA_VERIFIED_SHIFT = 5
DATA_VERIFICATION_DESIRED_SHIFT = 4
RESPONSE_CODE_SHIFT = 0

OPERATION_CODE_MASK = 0b1111

OPERATION_CODE_QUERY_STANDARD = 0
OPERATION_CODE_QUERY_INVERSE = 1
OPERATION_CODE_STATUS = 2

RESPONSE_CODE_MASK = 0b1111


RESPONSE_CODE_OK = 0
RESPONSE_CODE_FORMAT_ERROR = 1
RESPONSE_CODE_SERVER_FAILURE = 2
RESPONSE_CODE_DOMAIN_NON_EXISTENT = 3
RESPONSE_CODE_NOT_IMPLEMENTED = 4
RESPONSE_CODE_QUERY_REFUSED = 5
RESPONSE_CODE_NAME_EXISTS_BUT_SHOULD_NOT = 6
RESPONSE_CODE_RESOURCE_RECORD_EXISTS_WHEN_SHOULD_NOT = 7
RESPONSE_CODE_RESOURCE_RECORD_NOT_EXISTS_WHEN_SHOULD = 8
RESPONSE_CODE_SERVER_NOT_AUTHORITATIVE_FOR_ZONE = 9
RESPONSE_CODE_NOT_AUTHORIZED = 10
RESPONSE_CODE_NAME_NOT_IN_ZONE = 11
RESPONSE_CODE_BAD_OPTION_VERSION = 16
RESPONSE_CODE_TRANSACTION_SIGNATURE_FAILURE = 16
RESPONSE_CODE_KEY_NOT_RECOGNIZED = 17
RESPONSE_CODE_SIGNATURE_OUT_OF_TIME_WINDOW = 18
RESPONSE_CODE_BAD_TRANSACTION_KEY_MODE = 19
RESPONSE_CODE_DUPLICATE_KEY_NAME = 20
RESPONSE_CODE_ALGORITHM_NOT_SUPPORTED = 21
RESPONSE_CODE_BAD_TRUNCATION = 22
RESPONSE_CODE_BAD_OR_MISSING_SERVER_COOKIE = 23


CLASS_CODE_INTERNET = 1
CLASS_CODE_CHAOS = 3
CLASS_CODE_HESIOD = 4
CLASS_CODE_QUERY_CLASS_NONE = 254
CLASS_CODE_QUERY_CLASS_ANY = 255

# https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6
RESOURCE_RECORD_TYPE_IP_V4_ADDRESS = 1
RESOURCE_RECORD_TYPE_AUTHORITATIVE_NAME_SERVER = 2
RESOURCE_RECORD_TYPE_MAIL_DESTINATION = 3 # deprecated, use 15
RESOURCE_RECORD_TYPE_MAIL_FORWARDER = 4 # deprecated, use 15
RESOURCE_RECORD_TYPE_CANONICAL_NAME_FOR_AN_ALIAS = 5
RESOURCE_RECORD_TYPE_START_OF_ZONE_OF_AUTHORITY = 6
RESOURCE_RECORD_TYPE_MAIL_BOX_DOMAIN_NAME = 7 # experimental
RESOURCE_RECORD_TYPE_MAIL_GROUP_MEMBER = 8 # experimental
RESOURCE_RECORD_TYPE_MAIL_RENAME_DOMAIN_NAME = 9 # experimental
RESOURCE_RECORD_TYPE_NULL = 10 # experimental
RESOURCE_RECORD_TYPE_WELL_KNOWN_SERVICE_DESCRIPTION = 11
RESOURCE_RECORD_TYPE_DOMAIN_NAME_POINTER = 12
RESOURCE_RECORD_TYPE_HOST_INFORMATION = 13
RESOURCE_RECORD_TYPE_MAIL_BOX_OR_LIST_INFORMATION = 14
RESOURCE_RECORD_TYPE_MAIL_EXCHANGE = 15
RESOURCE_RECORD_TYPE_TEXT_STRINGS = 16
RESOURCE_RECORD_TYPE_RESPONSIBLE_PERSON = 17
RESOURCE_RECORD_TYPE_ANDREW_FILE_SYSTEM_DATA_BASE_LOCATION = 18
RESOURCE_RECORD_TYPE_X25_PUBLIC_SWITCHED_DATA_NETWORK_ADDRESS = 19
RESOURCE_RECORD_TYPE_INTEGRATED_SERVICE_DIGITAL_NETWORK_ADDRESS = 20
RESOURCE_RECORD_TYPE_NETWORK_SERVICE_ACCESS_POINT_ADDRESS = 22 # deprecated
RESOURCE_RECORD_TYPE_NETWORK_SERVICE_ACCESS_POINT_DOMAIN_NAME_POINTER = 23 # deprecated
RESOURCE_RECORD_TYPE_SECURITY_SIGNATURE = 24
RESOURCE_RECORD_TYPE_SECURITY_KEY = 25
RESOURCE_RECORD_TYPE_X400_MAIL_MAPPING_INFORMATION = 26
RESOURCE_RECORD_TYPE_GEOGRAPHICAL_POSITION = 27
RESOURCE_RECORD_TYPE_IP_V6_ADDRESS = 28
RESOURCE_RECORD_TYPE_LOCATION_INFORMATION = 29
RESOURCE_RECORD_TYPE_NEXT_DOMAIN = 30 # obsolete
RESOURCE_RECORD_TYPE_ENDPOINT_IDENTIFIER = 31
RESOURCE_RECORD_TYPE_NIMROD_LOCATOR = 32
RESOURCE_RECORD_TYPE_SERVER_SELECTION = 33
RESOURCE_RECORD_TYPE_AUTOMATED_TELLER_MACHINE_ADDRESS = 34
RESOURCE_RECORD_TYPE_NAMING_AUTHORITY_POINTER = 35
RESOURCE_RECORD_TYPE_KEY_EXCHANGER = 36
RESOURCE_RECORD_TYPE_CERTIFICATE = 37
RESOURCE_RECORD_TYPE_IP_V6_HOST_ADDRESS = 38 # deprecated, use 28
RESOURCE_RECORD_TYPE_DOMAIN_NAME = 39
RESOURCE_RECORD_TYPE_SINK = 40
RESOURCE_RECORD_TYPE_OPT = 41
RESOURCE_RECORD_TYPE_ADDRESS_PREFIX_LIST = 42
RESOURCE_RECORD_TYPE_DELEGATION_SIGNER = 43
RESOURCE_RECORD_TYPE_SSH_KEY_FINGERPRINT = 44
RESOURCE_RECORD_TYPE_IP_SECURITY_KEY = 45
RESOURCE_RECORD_TYPE_RESOURCE_RECORD_SIGNATURE = 46
RESOURCE_RECORD_TYPE_NEXT_SECURE = 47
RESOURCE_RECORD_TYPE_DOMAIN_NAME_SYSTEM_PUBLIC_KEY = 48
RESOURCE_RECORD_TYPE_DYNAMIC_HOST_CONFIGURATION_INFORMATION_DEFINITION = 49
RESOURCE_RECORD_TYPE_NAME_SECURITY_3 = 50
RESOURCE_RECORD_TYPE_NAME_SECURITY_3_PARAMETER = 51
RESOURCE_RECORD_TYPE_TRANSPORT_LAYER_SECURITY_AUTHENTICATION = 52
RESOURCE_RECORD_TYPE_SECURE_MULTIPURPOSE_INTERNET_MAIL_EXTENSION_CERTIFICATE_ASSOCIATION = 53
RESOURCE_RECORD_TYPE_HOST_IDENTITY_PROTOCOL = 55
RESOURCE_RECORD_TYPE_NETWORK_INFO = 56
RESOURCE_RECORD_TYPE_RECORD_KEY = 57
RESOURCE_RECORD_TYPE_TRUST_ANCHOR_LINK = 58
RESOURCE_RECORD_TYPE_CHILD_DELEGATION_SIGNER = 59
RESOURCE_RECORD_TYPE_CHILD_DOMAIN_NAME_SYSTEM_KEY = 60
RESOURCE_RECORD_TYPE_OPEN_PGP_KEY = 61
RESOURCE_RECORD_TYPE_CHILD_TO_PARENT_SYNCHRONIZATION = 62
RESOURCE_RECORD_TYPE_MESSAGE_DIGEST_OVER_ZONE_DATA = 63
RESOURCE_RECORD_TYPE_SERVE_BINDING = 64
RESOURCE_RECORD_TYPE_HYPER_TEXT_TRANSFER_PROTOCOL_SECURE = 65
RESOURCE_RECORD_TYPE_DELEGATION_SYNCHRONIZATION = 66
RESOURCE_RECORD_TYPE_HIERARCHY_HOST_IDENTITY_TAH = 67
RESOURCE_RECORD_TYPE_BROADCAST_REMOTE_IDENTIFICATION = 68
RESOURCE_RECORD_TYPE_SENDER_POLICY_FRAMEWORK = 99
RESOURCE_RECORD_TYPE_USER_INFO = 100
RESOURCE_RECORD_TYPE_USER_IDENTIFIER = 101
RESOURCE_RECORD_TYPE_GROUP_IDENTIFIER = 102
RESOURCE_RECORD_TYPE_UNSPECIFIED = 103
RESOURCE_RECORD_TYPE_IDENTIFIER_LOCATOR_NETWORK_SEARCH_PROTOCOL = 104
RESOURCE_RECORD_TYPE_LOCATOR_32_BIT = 105
RESOURCE_RECORD_TYPE_LOCATOR_64_BIT = 106
RESOURCE_RECORD_TYPE_LOCATOR_POINTER = 107
RESOURCE_RECORD_TYPE_EXTENDED_UNIQUE_IDENTIFIER_48_BIT = 108
RESOURCE_RECORD_TYPE_EXTENDED_UNIQUE_IDENTIFIER_64_BIT = 109
RESOURCE_RECORD_TYPE_NON_EXISTENT_DOMAIN = 128
RESOURCE_RECORD_TYPE_TRANSACTION_KEY = 249
RESOURCE_RECORD_TYPE_TRANSACTION_SIGNATURE = 250
RESOURCE_RECORD_TYPE_INCREMENT_TRANSFER = 251
RESOURCE_RECORD_TYPE_ZONE_TRANSFER = 252
RESOURCE_RECORD_TYPE_MAIL_BOX = 253
RESOURCE_RECORD_TYPE_MAIL_AGENT = 254
RESOURCE_RECORD_TYPE_ALL = 255
RESOURCE_RECORD_TYPE_UNIFORM_RESOURCE_IDENTIFIER = 256
RESOURCE_RECORD_TYPE_CERTIFICATION_AUTHORITY_RESTRICTION = 257
RESOURCE_RECORD_TYPE_APPLICATION_ACCESSIBILITY_AND_CONTROL = 258
RESOURCE_RECORD_TYPE_DIGITAL_OBJECT_ARCHITECTURE = 259
RESOURCE_RECORD_TYPE_AUTOMATIC_MULTICAST_TUNNELING_RELAY = 260
RESOURCE_RECORD_TYPE_RESOLVER_INFORMATION = 261
RESOURCE_RECORD_TYPE_WALLET = 262
RESOURCE_RECORD_TYPE_DELAY_TOLERANT_NETWORK_CONVERGENCE_LAYER_ADAPTER = 263
RESOURCE_RECORD_TYPE_DELAY_TOLERANT_NETWORK_INTEGER_BASED_NAMING = 264
RESOURCE_RECORD_TYPE_DOMAIN_NAME_SYSTEM_SECURITY_TRUTH_AUTHORITIES = 32768
RESOURCE_RECORD_TYPE_DOMAIN_NAME_SYSTEM_SECURITY_LOOKASIDE_VALIDATION = 32769 # obsolete

# Extended domain name system
# https://www.rfc-editor.org/rfc/rfc7828

OPTION_TYPE_KEEP_ALIVE = 11
