__all__ = ()

CODE_FLAG_OPTIMIZED = 1
CODE_FLAG_NEWLOCALS = 2
CODE_FLAG_VARARGS = 4
CODE_FLAG_VARKEYWORDS = 8
CODE_FLAG_NESTED = 16
CODE_FLAG_GENERATOR = 32
CODE_FLAG_NOFREE = 64
    
CODE_FLAG_COROUTINE = 128
CODE_FLAG_ITERABLE_COROUTINE = 256
CODE_FLAG_COROUTINE_GENERATOR = 512
# matches `async def` functions and `@coroutine` functions.
CODE_FLAG_COROUTINE_ALL = CODE_FLAG_COROUTINE | CODE_FLAG_ITERABLE_COROUTINE
